version: '3.8'
services:
  frontend:
    image: mohamedelhedilimem1/interview-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    image: mohamedelhedilimem1/interview-backend:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - interview-data:/app/data

volumes:
  interview-data: