name: My First Pipeline

on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      # NEW STEP - Checkout the code
      - name: Step 1 - Checkout Code
        uses: actions/checkout@v4

      # EXISTING STEP (now it's Step 2)
      - name: Step 2 - Print a Greeting
        run: echo "Hello World! My pipeline is starting!"

      # NEW STEP - See what files we have
      - name: Step 3 - List Files
        run: ls -la

      - name: Investigate the Runner
        run: |
          echo "Hello from the runner machine!"
          echo "My hostname is: $(hostname)"
          echo "I am running on: $(uname -s -m)" # Prints OS and architecture
          echo "My current directory is: $(pwd)"
          echo "The contents of this directory are:"
          ls -la
          echo "---"
          echo "This runner is provided by GitHub. I don't know its exact location, but I can see my IP:"
          curl -s ifconfig.me # This command gets your public IP
          echo ""
